/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardTemplateRouteImport } from './routes/dashboard-template'
import { Route as AddBookRouteImport } from './routes/add-book'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const DashboardTemplateRoute = DashboardTemplateRouteImport.update({
  id: '/dashboard-template',
  path: '/dashboard-template',
  getParentRoute: () => rootRouteImport,
} as any)
const AddBookRoute = AddBookRouteImport.update({
  id: '/add-book',
  path: '/add-book',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/add-book': typeof AddBookRoute
  '/dashboard-template': typeof DashboardTemplateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/add-book': typeof AddBookRoute
  '/dashboard-template': typeof DashboardTemplateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/add-book': typeof AddBookRoute
  '/dashboard-template': typeof DashboardTemplateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/add-book' | '/dashboard-template'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/add-book' | '/dashboard-template'
  id: '__root__' | '/' | '/about' | '/add-book' | '/dashboard-template'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AddBookRoute: typeof AddBookRoute
  DashboardTemplateRoute: typeof DashboardTemplateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard-template': {
      id: '/dashboard-template'
      path: '/dashboard-template'
      fullPath: '/dashboard-template'
      preLoaderRoute: typeof DashboardTemplateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-book': {
      id: '/add-book'
      path: '/add-book'
      fullPath: '/add-book'
      preLoaderRoute: typeof AddBookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AddBookRoute: AddBookRoute,
  DashboardTemplateRoute: DashboardTemplateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
